### ISSUE TITLE
Synchronization frequency is zero for certain parameter values

### ISSUE THREAD

**Issue by teambarrywhite** [cuichi23/delayCoupledDPLLnet#3]
For the parameter values: 

coupling strength K  [Hz]|filter_cutoff f_c  [Hz]|delay [s]|Omega [Hz]|m-twist-state|Tsim ~= - 25 / Re(lambda)|paramSet id|Re(\lambda)|Zeitproxy 1. simulation [sek]|topology|diff. const. c|# oscis|coupling function|Nx |Ny|mx|my
-------------------------|-----------------------|---------|----------|-------------|-------------------------|-----------|-----------|-----------------------------|--------|--------------|-------|-----------------|---|--|--|--
1|1|0.5|0|0|428|13|-0.0583493152|17|square-periodic|0|144|triang|12|12|0|0
1|1|0.5|1.3333333333|0|428|14|-0.0583493152|17|square-periodic|0|144|triang|12|12|0|0
1|1|0.5|0|0|958|62|-0.0261096195|38|square-open|0|144|triang|12|12|0|0
1|1|0.5|1.3333333333|0|958|63|-0.0261096195|38|square-open|0|144|triang|12|12|0|0

the global sync frequency is zero. Is this correct? If yes, what does it mean?

**Comment by teambarrywhite** [comment]
A global sync frequency of 0 is possible for kc=w and triangular coupling function

* h(0) = -1
* h_sum(0) = sum(c_kl * h(0)) = n_k * ((1/n_k) * h(0)) = -1
* sync freq equation: kc * tau h_sum(x) + w * tau - x == 0
* let x = 0 and kc = w := c: tau * (c * (-1) * c) == 0 -> True

Please note that these solutions cannot be computed by the parametric approach since tau = s / omega(s) yields a definition by zero.

**Comment by teambarrywhite** [comment]
How should we treat these states?

**Comment by cuichi23** [comment]
I will run a simulation... trying to start close to that state?

**Comment by teambarrywhite** [comment]
Great. Could you find the state in the simulation? Seems to stable for some parameter sets.

![download](https://user-images.githubusercontent.com/19612675/27121710-b3bb184c-50e8-11e7-9e31-a84a99dea326.png)

**Comment by teambarrywhite** [comment]
Simulations confirm that the state exists. If the state will be treated different than other states we do this outside synctools
