### ISSUE TITLE
utility function for generating delay plots in synctools

### ISSUE THREAD

**Issue by cuichi23** [cuichi23/delayCoupledDPLLnet#9]
Need a function in synctools that can be called with the Parameters topology, K, Fc, F, kx, ky, k, but not the delay. It should plot the frequencies of the specified state (ky,kx,k in a given topology) against the communication delay, as well as the largest real part lambda versus the delay. In both cases the delay should be in [0, 2*1/F), i.e., two eigenperiods.

**Comment by teambarrywhite** [comment]
Added to synctools_interface: generate_delay_plot

Has the same interface as the SweepFactory except for the delay tau and an optional argument for the filename of the saved plots.
